// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uetcinfovlvesgmnxvwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldGNpbmZvdmx2ZXNnbW54dndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTM0ODQsImV4cCI6MjA2OTQ2OTQ4NH0.0zKVlEre5f9H7KJAp3JI6lhtJcuCAYXsKkU2NllkWho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});